extends SceneTree
const State=preload("res://scripts/survival/state.gd")
var assertions:=0
var failures:=0
func check(ok: bool,message: String) -> void:
	assertions+=1
	if not ok: failures+=1;printerr("FAIL: ",message)
func _initialize() -> void:
	var s:=State.new()
	check(s.phase=="safe" and s.capacity()==6 and s.weapon().damage==34,"Starting equipment and carrying capacity")
	check(not s.spend_stamina(101) and s.stamina==100,"Unaffordable action spends nothing")
	s.begin_run()
	check(s.hurt(23)==23 and s.hp==77,"Unprotected damage")
	var coat:=s.make_item("coat");s.pickup(coat);s.equip(coat.uid)
	check(is_equal_approx(s.hurt(23),18.86),"Coat mitigates 18 percent")
	check(s.inventory.is_empty() and s.equipment.body.uid==coat.uid,"Worn gear frees bag slot")
	var pack:=s.make_item("pack");s.pickup(pack);s.equip(pack.uid)
	for i in range(8): check(s.pickup(s.make_item("water")),"Fill expanded pack "+str(i))
	var before:=s.serialize()
	check(not s.pickup(s.make_item("can")),"Full bag rejects pickup")
	check("腾出" in s.unequip("pack") and s.capacity()==8 and s.inventory.size()==8,"Cannot remove full expanded pack")
	check(s.equipment.pack==before.equipment.pack,"Failed gear change is atomic")
	check(not s.pickup(s.inventory[0]),"Duplicate instance rejected")
	var water: Dictionary=s.inventory[0].duplicate();s.hydration=20
	check(s.consume(water.uid) and s.hydration==65,"Water restores hydration")
	check(not s.consume(water.uid) and s.consumed.has(water.uid),"Consumable can only be consumed once")
	var dropped:=s.drop(s.inventory[0].uid)
	check(s.pickup(dropped),"Dropped instance may be picked up again")
	s.drop(s.inventory[0].uid);s.drop(s.inventory[0].uid)
	check(s.inventory.size()==5,"Bag reduced to five items")
	check("收回" in s.unequip("pack") and s.capacity()==6 and s.inventory.size()==6,"Pack removal at exact capacity")
	s.drop(s.inventory[0].uid)
	var bat:=s.make_item("bat");s.pickup(bat)
	check("已装备" in s.equip(bat.uid,"secondary"),"Secondary weapon accepted")
	check(s.swap_weapons() and s.weapon().damage==45 and s.equipment.secondary.id=="wrench","Swap preserves both instances")
	check(s.reward("one")==40 and s.reward("one")==0 and s.run_kills==1,"Death reward idempotent")
	s.reward("two");s.reward("three")
	check(s.level==2 and s.xp==20 and s.points==1,"Third kill crosses level threshold")
	check(s.add_attribute("strength") and is_equal_approx(s.damage_multiplier(),1.06),"Strength point changes damage")
	check(not s.add_attribute("constitution") and not s.add_attribute("invalid"),"Cannot spend nonexistent points")
	check(not s.reset_attributes(),"Respec available only in safety")
	var saved: Dictionary=JSON.parse_string(JSON.stringify(s.serialize()))
	var loaded:=State.new()
	check(loaded.restore(saved),"Complete state JSON round trip")
	check(loaded.equipment==s.equipment and loaded.inventory==s.inventory and loaded.rewarded==s.rewarded,"Round trip preserves instances and reward ledger")
	check(loaded.reward("three")==0,"Reload cannot award a death twice")
	s.hp=0;s.fail_run()
	check(s.phase=="dead" and s.inventory.is_empty(),"Death discards unbanked bag")
	check(s.equipment.primary.id=="wrench" and s.equipment.secondary.is_empty() and s.equipment.body.is_empty(),"Death restores departure gear, not newly found gear")
	check(s.level==2 and s.attributes.strength==1,"Death retains earned progression")
	check(loaded.restore(JSON.parse_string(JSON.stringify(s.serialize()))),"Death save restores")
	s.return_to_base();s.reset_attributes()
	check(s.points==1 and s.attributes.strength==0,"Safehouse refunds allocated points")
	s.add_attribute("constitution")
	check(s.maximum_hp()==110,"Constitution increases maximum HP")
	for i in range(2): s.pickup(s.make_item("water"))
	s.begin_run();s.extract()
	check(s.phase=="safe" and s.inventory.is_empty() and s.stash.size()==2 and s.mission_done,"Extraction banks water and completes objective")
	check(not s.extract() and s.stash.size()==2,"Extraction cannot duplicate loot")
	check(s.transfer(s.stash[0].uid,true) and s.stash.size()==1 and s.inventory.size()==1,"Withdraw from stash")
	check(s.transfer(s.inventory[0].uid,false) and s.stash.size()==2,"Deposit back to stash")
	s.begin_run()
	check(not s.transfer(s.stash[0].uid,true),"Cannot access stash outside safehouse")
	check(s.reward("one")==40,"New expedition has a fresh enemy reward ledger")
	s.nutrition=85;s.hydration=85;s.hp=40;s.stamina=0;s.exertion=0;s.hurt_cooldown=10
	s.tick(1)
	check(s.hp==40 and s.stamina>0,"Recent injury prevents passive healing, not stamina recovery")
	s.hurt_cooldown=0;s.tick(1)
	check(s.hp>40,"Well-fed out-of-combat regeneration")
	s.nutrition=20;s.hydration=20;s.stamina=100;s.tick(.01)
	check(s.maximum_stamina()==78 and s.stamina<=78,"Dehydration clamps stamina ceiling")
	check(s.statuses().size()>=2,"Hunger and dehydration both visible")
	s.stamina=0;s.tick(1)
	check(is_equal_approx(s.stamina,14.95),"Hunger lowers stamina recovery by 35 percent")
	var bar:=s.make_item("bar");s.pickup(bar);s.consume(bar.uid)
	check(s.energy_buff==45 and is_equal_approx(s.stamina,34.95),"Energy bar immediate recovery and timed buff")
	var bottle:=s.make_item("bottle");s.pickup(bottle)
	check(not s.consume(bottle.uid) and s.throw_bottle() and not s.throw_bottle(),"Bottle is throwable, not edible, and consumed once")
	s.reward("mass",10000)
	check(s.level==5 and s.xp==0 and s.points==3,"Level cap has bounded progression")
	for key in ["endurance","agility","strength"]: s.add_attribute(key)
	check(is_equal_approx(s.maximum_stamina(),85.8) and is_equal_approx(s.speed_multiplier(),1.02),"Endurance and agility affect derived stats")
	s.extract()
	check(loaded.restore(JSON.parse_string(JSON.stringify(s.serialize()))),"Capped profile round trip")
	var clean:=s.serialize()
	for change in [{"version":1},{"phase":"unknown"},{"level":99},{"hp":-2},{"xp":"40"},{"attributes":{}},{"inventory":[{"id":"unknown","uid":"a"}]},{"equipment":{}},{"departure_equipment":{}},{"rewarded":[12]},{"consumed":[null]},{"mission_done":"yes"},{"result_text":null}]:
		var bad:=clean.duplicate(true);bad.merge(change,true)
		# Empty departure snapshot is valid only in the safe phase.
		if change.has("departure_equipment"): bad.phase="run"
		var previous:=loaded.serialize()
		check(not loaded.restore(bad),"Reject malformed field "+str(change.keys()[0]))
		check(loaded.serialize()==previous,"Invalid restore is atomic for "+str(change.keys()[0]))
	var duplicate:=clean.duplicate(true);duplicate.inventory=[duplicate.equipment.primary.duplicate()]
	check(not loaded.restore(duplicate),"Save rejects item duplicated across equipment and inventory")
	print("SURVIVAL_STATE_TESTS: ",assertions," assertions, ",failures," failures")
	quit(1 if failures else 0)
