extends SceneTree
var game: Node3D
var assertions:=0
var failures:=0
func _initialize() -> void: call_deferred("run")
func check(ok: bool,message: String) -> void:
	assertions+=1
	if not ok: failures+=1;printerr("FAIL: ",message)
func frames(count: int=3) -> void:
	for i in range(count): await physics_frame
func freeze_enemies() -> void:
	for enemy in game.enemies: enemy.set_physics_process(false)
func aim(id: String) -> void:
	game.player.velocity=Vector3.ZERO;game.player.impulse=Vector3.ZERO;game.player.kick=0;game.player.roll=0
	game.player.active=false;game.player.position=Vector3(-1.22,.04,-4.02);game.player.face(game.sources[id].position)
	await frames();game.update_target()
func begin(source: SurvivalSearchable) -> void:
	game.combat.reset();Input.action_press("interact");game.start_search(source)
func stop() -> void:
	Input.action_release("interact");game.cancel_search();game.close_search_results()
func run() -> void:
	game=load("res://scenes/survival.tscn").instantiate()
	game.save_path="user://survival-search-test.json";game.settings_path="user://survival-search-settings.json"
	DirAccess.remove_absolute(game.save_path);DirAccess.remove_absolute(game.settings_path)
	root.add_child(game);game.set_process(false);game.combat.set_process(false)
	await frames()
	game.new_profile();game.depart();freeze_enemies();await frames()
	var source: SurvivalSearchable=game.sources["kitchen-box"]
	var item: Dictionary=source.contents[0].duplicate(true)
	await aim("kitchen-box")
	check(game.target==source and game.source_reachable(source),"Kitchen box is selectable through the actual physics ray")
	check(not source.take(item.uid,game.state) and source.contents.size()==2,"Unsearched contents cannot be claimed through the API")
	begin(source);game.update_search(.6)
	check(game.ui.search_spinner.visible and not source.searched and game.state.inventory.is_empty(),"Partial search shows progress without revealing or granting loot")
	Input.action_release("interact");game.update_search(.8)
	check(game.search_id.is_empty() and not source.searched and not game.ui.search_spinner.visible,"Releasing E cancels search")
	begin(source);game.update_search(.6);game.player.face(Vector3(1,1,-1));await frames();game.update_target();game.update_search(.8)
	check(game.search_id.is_empty() and not source.searched,"Looking away cancels search")
	await aim("kitchen-box");begin(source);game.update_search(.6);game.player_hit(1,game.player.position+Vector3.RIGHT)
	check(game.search_id.is_empty() and not source.searched,"Damage cancels search without revealing contents")
	await aim("kitchen-box");begin(source);game.update_search(.6);game.pause_game()
	check(not source.searched and game.search_id.is_empty() and game.suspended,"Pause cancels a partial search")
	game.resume_game();await aim("kitchen-box");begin(source);game.update_search(.6);game.combat.press()
	check(not source.searched and game.search_id.is_empty(),"An attack cancels a partial search")
	game.combat.reset();begin(source);game.player.position=Vector3(0,.04,2.1);game.update_search(2)
	check(not source.searched and game.search_id.is_empty(),"Moving beyond reach cancels search")
	await aim("kitchen-box");begin(source);game.update_search(source.duration+.01);Input.action_release("interact")
	check(source.searched and game.ui.view=="search" and not game.suspended,"Completed search reveals results in a live world")
	check(game.state.inventory.is_empty() and source.contents.size()==2,"Finishing search does not grant items automatically")
	for i in range(6): game.state.pickup(game.state.make_item("can"))
	game.ui.refresh_search(source,game.state)
	check(game.ui.search_take_all.disabled,"Take-all is disabled when the bag is full")
	game.take_from_source()
	check(source.contents.size()==2 and not game.state.owns_uid(item.uid),"Full bag preserves all contents even when the action is called directly")
	game.state.drop(game.state.inventory[0].uid)
	game.take_from_source()
	check(game.state.inventory.size()==6 and source.contents.size()==1 and game.state.owns_uid(item.uid),"Take-all fills available space and leaves the rest at the source")
	game.take_from_source(item.uid)
	check(source.contents.size()==1 and game.state.inventory.size()==6,"Duplicate claim does not remove another item")
	game.player_hit(1,game.player.position+Vector3.RIGHT)
	check(game.ui.view=="game" and game.active_source_id.is_empty(),"Damage closes the loot panel and restores combat")
	await aim("kitchen-box");game.start_search(source)
	check(game.ui.view=="search" and game.search_id.is_empty(),"An already searched source reopens immediately")
	var profile: Dictionary=game.state.serialize()
	var partial: Dictionary=game.snapshot()
	check(partial.schema==3 and not partial.has("loot"),"Version 3 stores finite sources, not loose-item drops")
	game.state.restore(profile);game.restore_run(partial);freeze_enemies();await frames()
	source=game.sources["kitchen-box"]
	check(source.searched and source.contents.size()==1 and game.state.owns_uid(item.uid),"Reload preserves partial collection and search completion")
	check(not game.sources.cabinet.searched and game.sources.cabinet.contents.size()==2,"Reload preserves unopened cabinet contents")
	game.resume_game();await aim("kitchen-box");game.start_search(source)
	game.state.drop(game.state.inventory[0].uid);game.take_from_source()
	check(source.contents.is_empty(),"Last item can be taken after making space")
	game.close_search_results();game.start_search(source);game.take_from_source()
	check(source.contents.is_empty() and source.description()=="已搜空","Reopening an empty source never rerolls supplies")
	game.player.position=Vector3(1,.04,2);game.update_search(.1)
	check(game.ui.view=="game","Moving away closes the results and blocks remote claiming")
	# A physically occluded source cannot be searched or collected remotely.
	var behind: SurvivalSearchable=game.spawn_source("occluded","测试柜",Vector3(3.5,1,-2),[game.state.make_item("water")])
	game.player.position=Vector3(2.5,.04,-2);await frames()
	check(not game.source_reachable(behind),"Partition blocks search line of sight")
	# Corpse contents and XP have separate lifetimes.
	var enemy=game.enemies[0]
	var count_before: int=game.sources.size();enemy.receive_hit(100,Vector3.ZERO,0)
	check(game.state.xp==40 and game.sources.size()==count_before+1 and game.loot.is_empty(),"Death grants XP and creates exactly one corpse source")
	enemy.animate(3);game.update_sources()
	var corpse: SurvivalSearchable=game.sources["corpse-"+enemy.enemy_id]
	check(corpse.kind=="corpse" and not corpse.searched and corpse.contents.size()==1,"Dead enemy retains its unrevealed weapon")
	check(corpse.position.distance_to(enemy.corpse_point())<.01 and corpse.position.y<.4,"Search zone follows the animated fallen pelvis")
	game.enemy_killed(enemy)
	check(game.state.xp==40 and game.sources.size()==count_before+1,"Repeated death callback creates neither extra XP nor another source")
	var saved: Dictionary=game.snapshot();game.state.restore(saved.profile);game.restore_run(saved);freeze_enemies();await frames()
	game.update_sources()
	check(game.sources["corpse-living-infected"].contents.size()==1 and game.enemies[0].health==0,"Reload preserves corpse inventory and death pose")
	# Migrate an exact legacy state: picked/consumed items must never regenerate.
	game.new_profile();game.depart();freeze_enemies();await frames()
	var owned: Dictionary=game.state.make_item("water");game.state.pickup(owned)
	var consumed: Dictionary=game.state.make_item("bar");game.state.pickup(consumed);game.state.consume(consumed.uid)
	var remaining: Dictionary=game.state.make_item("can")
	var bat: Dictionary=game.state.make_item("bat")
	game.enemies[0].receive_hit(100,Vector3.ZERO,0)
	var old: Dictionary=game.snapshot();old.schema=2;old.erase("sources");old.erase("map_revision");old.erase("ranged_revision")
	old.enemies=old.enemies.filter(func(e): return e.id in ["living-infected","hall-infected","storage-infected"])
	old.loot=[{"id":"water-kitchen","item":owned},{"id":"energy-counter","item":consumed},{"id":"food-cabinet","item":remaining},{"id":"drop-living-infected","item":bat},{"id":"duplicate","item":remaining}]
	game.state.restore(old.profile);game.restore_run(old);freeze_enemies();await frames()
	check(game.valid_snapshot(old),"Legacy version 2 snapshots remain supported")
	check(game.sources["kitchen-box"].contents.is_empty() and game.sources["storage-rack"].contents.is_empty(),"Legacy migration never refills removed world supplies")
	check(game.sources.cabinet.contents.size()==1 and game.sources.cabinet.contents[0].uid==remaining.uid,"Legacy remaining cupboard item is preserved exactly once")
	check(game.sources["corpse-living-infected"].contents[0].uid==bat.uid and game.state.xp==40,"Legacy death drop moves into its corpse without another reward")
	check(game.state.owns_uid(owned.uid) and game.state.consumed.has(consumed.uid),"Migration preserves owned and consumed item history")
	var total:=0
	for container in game.sources.values(): total+=container.contents.size()
	check(total==21 and game.snapshot().schema==3 and game.snapshot().map_revision==2,"Migration keeps two legacy items, adds 19 east-wing supplies including ranged equipment once, and writes map revision 2")
	# Weapon mechanics: different visible paths, windows, hands, impacts and charge thresholds.
	game.resume_game();game.combat.reset();game.state.stamina=100
	check(game.combat.start_swing(false),"Wrench light swing starts")
	var wrench: Dictionary=game.combat.profile.duplicate();var wrench_pose: Array=game.combat.swing_pose(wrench.contact)
	game.combat._process(wrench.contact-.01)
	check(not game.combat.hit_done,"Wrench cannot hit before its contact frame")
	game.combat._process(.02)
	check(game.combat.hit_done,"Wrench resolves on its own contact frame")
	check(not game.combat.start_swing(false),"Input spam cannot bypass recovery")
	var side_before: float=game.combat.side;game.combat.reset();game.combat.start_swing(false)
	check(game.combat.side==-side_before,"Wrench alternates left and right light attacks")
	game.combat.reset();game.combat.press();game.combat.elapsed=.4;game.combat.release()
	check(game.combat.heavy,"Wrench charges a heavy strike after 0.36 seconds")
	var bat_item: Dictionary=game.state.make_item("bat");game.state.pickup(bat_item);game.state.equip(bat_item.uid);game.combat.reset();game.state.stamina=100
	game.combat.start_swing(false)
	var bat_profile: Dictionary=game.combat.profile;var bat_pose: Array=game.combat.swing_pose(bat_profile.contact)
	check(game.combat.support_hand.visible and not game.combat.torch_hand.visible,"Bat uses a second support hand and clips the lamp to the chest")
	check(bat_profile.contact>wrench.contact and bat_profile.duration>wrench.duration,"Bat has later contact and longer recovery")
	check(bat_profile.radius>wrench.radius and bat_profile.stop>wrench.stop and bat_profile.force>wrench.force,"Bat has a wider impact zone, stronger hit stop and shove")
	check(bat_profile.audio!=wrench.audio and bat_pose[1].distance_to(wrench_pose[1])>10,"Weapons use distinct sound layers and contact poses")
	game.combat._process(.13)
	check(not game.combat.hit_done,"Bat does not reuse the wrench's early contact window")
	game.combat.reset();game.combat.press();game.combat.elapsed=.4;game.combat.release()
	check(not game.combat.heavy,"A 0.4 second hold is still a light bat attack")
	game.combat.reset();game.combat.press();game.combat.elapsed=.56;game.combat.release()
	check(game.combat.heavy,"Bat heavy strike requires its longer 0.55 second charge")
	game.combat.reset();game.state.stamina=0
	check(not game.combat.start_swing(true) and game.combat.phase=="idle","Insufficient stamina rejects a heavy attack without starting its animation")
	game.combat.reset();game.state.inventory.clear()
	var bottle: Dictionary=game.state.make_item("bottle");game.state.pickup(bottle)
	game.throw_bottle();game.combat._process(.12)
	check(game.combat.held_bottle.visible and game.state.owns_uid(bottle.uid) and game.projectiles.is_empty(),"Throw has a visible bottle windup before consumption")
	game.player_hit(1,game.player.position+Vector3.RIGHT);game.combat._process(.2)
	check(game.state.owns_uid(bottle.uid) and game.projectiles.is_empty() and not game.combat.held_bottle.visible,"Damage interrupts throwing without losing the bottle")
	game.combat.reset();game.throw_bottle();game.combat._process(.25);game.combat._process(.1)
	check(game.projectiles.size()==1 and not game.state.owns_uid(bottle.uid),"Overhand release creates one projectile and consumes once")
	for name in ["search","wrench_swing","bat_swing","wrench_contact","bat_contact"]:
		check(ResourceLoader.exists("res://assets/audio/"+name+".wav"),"Required sound resource exists: "+name)
	stop();game.effects.stop_audio();await frames(15);game.queue_free();await frames()
	DirAccess.remove_absolute("user://survival-search-test.json");DirAccess.remove_absolute("user://survival-search-settings.json")
	print("SURVIVAL_SEARCH_TESTS: ",assertions," assertions, ",failures," failures")
	quit(1 if failures else 0)
